### ISSUE TITLE
dashoard - Issue with the hyperlinks

### ISSUE THREAD

**Issue by vanishan** [pythonindia/junction#259]
The hyperlinks on total count in type based and section based proposal statistics takes to proposal page by default and no filter applied.
Url/filter criteria needs to be fixed.

**Comment by vnbang2003** [comment]
I had removed -- in url for poroposal-list  not where when it was added back.

url(r'^(?P<conference_slug>[\w-]+)/proposals/', include('junction.proposals.urls')),
url(r'^(?P<conference_slug>[\w-]+)--/',
        RedirectView.as_view(pattern_name="proposals-list"),
        name='conference-detail'),

The fix for it name the first url to proposals-page or similar and use this in named url of dashboard page.

**Comment by vnbang2003** [comment]
I have committed the fix. https://github.com/pythonindia/junction/commit/f257fea6f4f32117cb15b794efc74ee8308af50d
