### ISSUE TITLE
Namespace the URLs by year

### ISSUE THREAD

**Issue by nibrahim** [pythonindia/junction#453]
The website has some parts that are namespaced by year (e.g. in.pycon.org/2016 for the main page) but some parts that are namespaced by functionality (e.g. https://in.pycon.org/cfp/2016/proposals/). This is confusing in many ways. e.g.
  - Some pages are not really part of any conference (e.g. https://in.pycon.org/cfp/)
  - Some pages use the wrong theme (e.g. https://in.pycon.org/blog/2015/) uses the theme for 2016 which is confusing. 

There is also the longer term issue of archival. The earlier PyCons were hosted under a top level URL for the appropriate year and the entire app/pages were anchored from that as a root. A separate instance of the app would run at that URL and once the conference is over, the entire thing could be `wget`ted and archived as static pages (including the blog). The app would no longer need to run at those URLs.

**Comment by kracekumar** [comment]
> Some pages are not really part of any conference (e.g. https://in.pycon.org/cfp/)

Since 2012 CFP follows the current pattern but URL may be different [0]. I am aware PyCon US does `/2016/speaking/` but the contents is  unavailable for public. The selected proposals details are part of schedule. Every year, they clear database. If we follow same path every year new instance of the junction should be setup. Junction is not only used by PyCon India, there are other conferences using it now. PyDelhi [1] and PyBelgaum [2].  More conference may/will use in future. People who run this may not have experience of setting up django. Setting up this every year is time consuming and resentful experience of using junction. Once it is setup, the software runs and no intervention.

Junction can have the feature of blog and static site generator (page). Again the complexity of using the software increases.

From 2012 to 2014, the proposals are available at `in.pycon.org/funnel` [3], [4], [5].

The team be careful in choosing slug like `in.pycon.org/cfp/2016/proposals/` rather than `in.pycon.org/cfp/pycon-india-2015/proposals/`. As of  `in.pycon.org/cfp/2016/` is returning 404. The URL can display the list of proposals of the conference.

Changing the theme of junction same as year's website is arduous task. All the elements need css revamp and as functionality grows the task becomes unmanageable.

> Some pages use the wrong theme (e.g. https://in.pycon.org/blog/2015/) uses the theme for 2016 which is confusing.

Blog is continuous stream rather than the part of the specific year. Blog runs on [Pelican static generator](https://github.com/pythonindia/inpycon-blog). Every year changing the theme is hard. We hire design agency to do static website. The agency doesn't have expertise on static generator of our choice. Some in future may have. Last but not least, Pelican doesn't support many themes. Content can create blog post without worrying theme. Setting blog engine every year kills lot of time. It comes with its own baggage. Previous years this wasn't easy.

[0]: https://in.pycon.org/funnel/2014/115-security-toolsmithing-writing-security-tools-in-python/
[3]: https://in.pycon.org/2012/funnel/pyconindia2012/
[4]: https://in.pycon.org/funnel/2013/
[5]: https://in.pycon.org/funnel/2014/
[1]: https://cfp.pydelhi.org/pydelhi-conference-2016/proposals/
[2]: http://junction.pybelgaum.org/pybelgaum/proposals/

**Comment by nibrahim** [comment]
I see that with 2012, the funnel is namespaced under the year https://in.pycon.org/2012/funnel/pyconindia2012/ but after that, you're right, it's funnel/year. 

But before the implementation details, do you think it's worth doing? If so, we can find a path of least resistance. Otherwise, we can drop it without wasting time on the technical details.

**Comment by kracekumar** [comment]
I find value for blog at least and not CFP.

**Comment by theskumar** [comment]
I agree with @kracekumar and can't see this discussion relating to junction now. I'm closing the ticket. Thanks @nibrahim, but sorry we really don't much choice. Blog discussion can be moved to https://github.com/pythonindia/inpycon-blog.

Best.
