### ISSUE TITLE
git clone missing in Readme file

### ISSUE THREAD

**Issue by Vibhu-Agarwal** [pythonindia/junction#565]
No instructions to tell about cloning the project before setting up for the project
In [readme](https://github.com/pythonindia/junction#setup) `pip install -r requirements-dev.txt` gives error `Could not open requirements file: [Errno 2] No such file or directory: 'requirements-dev.txt'`

**Comment by ananyo2012** [comment]
@Vibhu-Agarwal Cloning is the first thing you do when you start working on a project. It is equivalent to downloading the project. So that's not required to be mentioned IMO. But yes for a complete first timer who is unknown to open source and git this may be unknown. We can add links to some good articles on git atmost.
