### ISSUE TITLE
No need to validate email on signup

### ISSUE THREAD

**Issue by anandology** [pythonindia/junction#59]
I've tried to register at junction.pybelgaum.org using my github account and it took me to [VERIFY YOUR E-MAIL ADDRESS](http://junction.pybelgaum.org/accounts/confirm-email/) page. 

Since I'm logging in using github, it is possible to access my already confirmed email address from github. There is no need to send confirmation email. 

The GitHub API for getting user email addresses of users is documented at:
https://developer.github.com/v3/users/emails/

**Comment by theskumar** [comment]
Keeping this low priority, because of the following reasons:

1. Email verification is applicable to all services, and making an exception for Github requires substantial refactoring/adding code to this project.
2. The thirty-party auth is handled by django-auth[1], maybe it will be in best interest to open a PR in the library instead of hacking into it.

That said, it definitely has definitely a usability advantage, and if someone would like to pick this up and make it work as expected. We are happy have it integrated.

[1]: https://github.com/pennersr/django-allauth

**Comment by pythonhacker** [comment]
Suggest to be marked for closing as WONTFIX. Reasons - > 2 years, and not critical.
