### ISSUE TITLE
Issue while setting up in windows 10

### ISSUE THREAD

**Issue by sameer1001** [pythonindia/junction#651]
Python version: 3.5 
Windows 10 Pro, version:  1903

While running **nox -- migrate --noinput** for the first time, we are getting an issue saying 
**AttributeError: module 'os' has no attribute 'uname'**

With quick googling, I could figure out that this is related to the package **uwsgi==2.0.*** in the **requirements.txt**

I removed this package from requirements.txt and tried running the command again and it worked. 

Everything seems to work fine after this also. I am not sure about the purpose of this package, so I thought of putting this as an issue here. 
 
Thanks,

**Comment by ananyo2012** [comment]
uWSGI is used for interacting between server and django app. While django launches a test server when using locally that is not enough for running in production.

The solution will be to move it in a separate requirements file `requirements-prod.txt` until we have some better dependency management solution like `pipenv`

**Comment by palnabarun** [comment]
@sameer1001 -- Thanks for filing this.

Last time I checked, none of the popular WSGI frameworks, viz, uWSGI or Gunicorn, support Windows due to the way they work. Ideally, uWSGI as a dependency should not be put in `requirements.txt` since it is not part of the application but is used to deploy WSGI applications.

**Comment by ananyo2012** [comment]
dockerized setup works in windows.
