### ISSUE TITLE
Issues while running nox to do the local development

### ISSUE THREAD

**Issue by sks444** [pythonindia/junction#660]
Our [development guide](https://github.com/pythonindia/junction/blob/master/docs/source/development/getting-started.rst) recommends to use `nox` for local development. But I have been facing few challenges while running it locally on mac system.

- `nox -- migrate --noinput` and `nox -- sample_data` results in following error:
```
nox > Running session dev
nox > Session dev skipped: Python interpreter 3.5 not found.
```
- Whereas while running `nox -s lint` I get the following error:
```
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/sks/sks444/junction/.nox/lint-3-7/bin/python', '-mvirtualenv', '/Users/sks/.cache/pre-commit/reposx0jtqg6/py_env-python3.6', '-p', 'python3.6')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.6'

stderr: (none)
Check the log at /Users/sks/.cache/pre-commit/pre-commit.log
nox > Command pre-commit run --all-files failed with exit code 1
nox > Session lint-3.7 failed.
nox > Running session lint-3.8
nox > Session lint-3.8 skipped: Python interpreter 3.8 not found.
nox > Ran multiple sessions:
nox > * lint-3.5: skipped
nox > * lint-3.6: skipped
nox > * lint-3.7: failed
nox > * lint-3.8: skipped
```
It seems we need to have `Python 3.5` and `Python 3.6` installed in our system to make these command works. But I already have two latest version of `Python: (3.7 and 3. 8)`, shouldn't that be enough, should I go ahead and install the other versions of Python?

On a further note `nox -s tests` is failing with a different error:
```
nox > Error while collecting sessions.
nox > Sessions not found: tests
```

**Comment by pradyunsg** [comment]
Ah, this helps understand the problem.

The underlying issue here is not with nox, but the use of an (EOL) version of Django in Junction. Django 1.9 on doesn't work on newer interpreters, and to avoid needing potential contributors to install too many interpreters, all the automation uses Python 3.5 (or 3.6 when that's not possible).

I guess we could bump everything to 3.6, but beyond that might get tricky. IIUC, someone will be working on upgrading junction to newer versions of Django sometime soon, and then we can resolve this issue.

And, the tests should be run with `nox -s test`; I made a typo in the documentation! Thanks for reporting that! ^>^

**Comment by ananyo2012** [comment]
@pradyunsg Shouldn't we let nox pickup the default python version available in developers environment for session dev ? Also we are forcing devs currently to test on all python3 versions. I think that shouldn't be the case. Nox should skip the test/lint session for the python versions that are not available.

**Comment by pradyunsg** [comment]
> Shouldn't we let nox pickup the default python version available in developers environment for session dev ?

Well... Once we upgrade to a decent version of Django, yes.

> Nox should skip the test/lint session for the python versions that are not available.

It does that by default: https://nox.readthedocs.io/en/stable/usage.html#opt-error-on-missing-interpreters

> Also we are forcing devs currently to test on all python3 versions. I think that shouldn't be the case. 

Yea, well, it's not forcing anything? I guess we can tell people to use `nox -s test-X.Y` instead. Feel free to file a PR updating the documentation to add this suggestion.

**Comment by ananyo2012** [comment]
We recently got a report of the first issue again. Until we migrate to a higher version of Python we need to let nox select the default available version of Python3. @pradyunsg I see the tests are passing for Python 3.6+ in CI with the current version of Django. What are the issues you were mentioning earlier ?

**Comment by pradyunsg** [comment]
FWIW, I'd like for us to be on the latest Python versions if possible, but I don't remember anymore what the roadmap was in my head.

I've paged this project outta my head by now, so I don't really know this off handedly. I do remember that this specific change wasn't as straightforward as bump everything to 3.8 (or even python="3", but I don't remember *why*/how I'd reached that conclusion.

I also don't remember what exactly the issue was w/ Django + Python 3.6. The test suite is not very comprehensive IIRC, so it passes the tests isn't a good metric for this project TBH. :)

**Comment by gutsytechster** [comment]
I am also facing the similar issue. I have `Python 3.6.5` installed on the system I am setting up the project. But when I run `nox -- migrate --no-input`, it exits with an error as

```
nox > Running session dev
nox > Session dev skipped: Python interpreter 3.5 not found.
```

I assume, this is because of this line [here](https://github.com/pythonindia/junction/blob/master/noxfile.py#L11). Can we also support `Python 3.6` for `dev` session or is it because `Django 1.9` does not support `Python 3.6` officially?

**Comment by ananyo2012** [comment]
#694 should fix this
