### ISSUE TITLE
Add blog URL to video feature help text

### ISSUE THREAD

**Issue by vipulgupta2048** [pythonindia/junction#701]
https://github.com/pythonindia/junction/blob/db766c2d1730994a42484e357b23b9654622532e/junction/proposals/forms.py#L117

The help text could be, 
`Short 1-3 min video describing your talk following the [best practices](https://in.pycon.org/blog/2020/2020-call-for-proposals-announcement.html)`

**Comment by anistark** [comment]
We seem to have discussed something on this. @palnabarun Do you happen to remember what was discussed about this?

**Comment by palnabarun** [comment]
@anistark I don't remember exactly what we discussed. But, my opinion is to put the Best Practices link at the top of the create proposal form.

Also, right now we have best practices on the wiki as well as the blog. I would prefer the content to be there in the wiki since the ref is mostly guaranteed to not change.
