### ISSUE TITLE
Add sub-category support in Junction

### ISSUE THREAD

**Issue by soumendrak** [pythonindia/junction#756]
![Image](https://user-images.githubusercontent.com/10120538/234049814-32a5e4f7-b4c0-4eba-acd0-438a65a6e2cb.png)
_PyCon 2019 CFP distribution_

The _"Data Science, AI, and ML"_ category generally receives approximately 50% of all talk proposals. Therefore, it becomes challenging to manage.

There was a proposal on the last All-Hands-volunteer-meet that if we can support _Sub-categories_, it will be helpful to manage from both Proposers and Reviewer's sides.

For example, _"Data Science, AI, and ML"_ category can have the following sub-categories:

- Generative AI
- Computer Vision
- NLP
- Data Visualization
- Data Analytics
- Data Engineering and further

**Comment by inovizz** [comment]
The work to be done is on branch `feature/upgrade-junction`

**Comment by inovizz** [comment]
yes, for sure. Please feel free to ask questions here or on Zulip.

**Comment by realslimshanky** [comment]
@soumendrak do you have a list of sub-categories already? We need a list per category.

**Comment by soumendrak** [comment]
@realslimshanky I will share the initial draft by tomorrow.

**Comment by kalyan678** [comment]
Under this category - Data Science, AI, and ML"  you can also include few more subcategories like

1. Machine Learning
2. Deep Learning
3. Reinforcement Learning
4. Natural languages Processing 
5. Computer Vision

I see computer vision and nlp are missing in the existing subcategories list so I added here :)

**Comment by Beingfarazkhan** [comment]
Can I add subcategories in web development category? Including python frameworks like django, flask, falcon, pyramid, fastapi and web2py

**Comment by palnabarun** [comment]
My 2p: Let's not hardcode subcategories. What is being referred in the issue is the type `ProposalSection`. To extend the functionality, a new type like `ProposalSubSection` should be created. The values for this type should be populated from the admin UI.

Whatever is being populated from the UI can then be used by proposal authors when submitting their proposal.

Broadly, this is what should be done:
- Create a new model `ProposalSubSection`
- Extend the `ProposalSection` model with reference to `ProposalSubSection` or the other way around (whichever is more feasible and canonical)
- Check if anything needs to be done on the Admin UI side of things to enable Conference Organisers to add values for Proposal Sub Section
- Add a dropdown to the New Proposal form for the subsection (to start with the value can be optional).

**Comment by miphilomath** [comment]
I can work on the approach shared by Nabarun.

**Comment by ananyo2012** [comment]
@miphilomath I think it will more streamlined to have specific sub sections for a proposal. So as suggested by Nabarun `ProposalSubSection` should have many to one relation with `ProposalSection`. The Proposal form should have a dropdown of subsection which will have the related items based on the chosen section.

**Comment by soumendrak** [comment]
We managed without this feature, closing the issue.
